#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="$ROOT_DIR/assets/review"
RAW_DIR="$OUT_DIR/raw"
IMG_DIR="$OUT_DIR/images"

if [[ -x "$ROOT_DIR/.venv/bin/python" ]]; then
  PYTHON_BIN="$ROOT_DIR/.venv/bin/python"
elif command -v python3 >/dev/null 2>&1; then
  PYTHON_BIN="python3"
else
  PYTHON_BIN="python"
fi

die_with_setup_hint() {
  echo "$1" >&2
  echo "Install dependencies with: uv sync --extra dev" >&2
  exit 1
}

if ! PYTHONPATH="$ROOT_DIR/src${PYTHONPATH:+:$PYTHONPATH}" \
  "$PYTHON_BIN" -c "import csvplot.cli" >/dev/null 2>&1; then
  die_with_setup_hint "Unable to run csvplot with '$PYTHON_BIN'."
fi

if ! "$PYTHON_BIN" -c "import plotext, rich, typer" >/dev/null 2>&1; then
  die_with_setup_hint "Missing runtime dependencies for '$PYTHON_BIN' (plotext/rich/typer)."
fi

RENDER_PYTHON="$PYTHON_BIN"
if ! "$RENDER_PYTHON" -c "import PIL" >/dev/null 2>&1; then
  if command -v python3 >/dev/null 2>&1 && python3 -c "import PIL" >/dev/null 2>&1; then
    RENDER_PYTHON="python3"
  else
    die_with_setup_hint "Pillow (PIL) is required to render PNG images."
  fi
fi

mkdir -p "$RAW_DIR" "$IMG_DIR"

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

run_csvplot() {
  PYTHONPATH="$ROOT_DIR/src${PYTHONPATH:+:$PYTHONPATH}" \
    "$PYTHON_BIN" -m csvplot "$@"
}

render_visual_png() {
  local slug="$1"
  local title="$2"
  shift 2
  local visual_txt="$RAW_DIR/${slug}.visual.txt"

  run_csvplot "$@" --format visual > "$visual_txt"
  "$RENDER_PYTHON" "$ROOT_DIR/scripts/render_terminal_png.py" \
    "$visual_txt" "$IMG_DIR/${slug}.png" --title "$title"
}

# Timeline
render_visual_png timeline_legend "timeline legend review" \
  timeline -f "$ROOT_DIR/data/timeplot.csv" \
  --x DH_PV_STARTDATUM --x DH_PV_EINDDATUM \
  --x EN_START_DATETIME --x EA_END_DATETIME \
  --y DH_FACING_NUMMER --color SH_ARTIKEL_S1 \
  --head 12 --marker 2025-01-22 --marker-label wissel-datum

render_visual_png timeline_zoom "timeline zoom review" \
  timeline -f "$ROOT_DIR/data/projects.csv" \
  --x start_date --x end_date --y project --color status \
  --from 2026-01-01 --to 2026-04-01

# Bar
render_visual_png bar_distribution "bar distribution review" \
  bar -f "$ROOT_DIR/data/titanic.csv" -c Pclass --sort value

render_visual_png bar_sort_top "bar sort top review" \
  bar -f "$ROOT_DIR/data/titanic.csv" -c Embarked --sort label --top 3

# Line
render_visual_png line_trend "line trend review" \
  line -f "$ROOT_DIR/data/temperatures.csv" --x Date --y Temp

render_visual_png line_head "line head review" \
  line -f "$ROOT_DIR/data/temperatures.csv" --x Date --y Temp --head 100

# Bubble
render_visual_png bubble_matrix "bubble matrix review" \
  bubble -f "$ROOT_DIR/data/titanic.csv" \
  --cols Cabin --cols Age --cols Embarked --y Name --head 12

render_visual_png bubble_top "bubble top review" \
  bubble -f "$ROOT_DIR/data/titanic.csv" \
  --cols Cabin --cols Age --cols Embarked --y Name --top 2 --head 12

# Bubble color behavior check (visual mode diff).
run_csvplot bubble -f "$ROOT_DIR/data/titanic.csv" \
  --cols Cabin --cols Age --cols Embarked --y Name --head 12 \
  > "$RAW_DIR/bubble_color_off.visual.txt"

run_csvplot bubble -f "$ROOT_DIR/data/titanic.csv" \
  --cols Cabin --cols Age --cols Embarked --y Name --color Pclass --head 12 \
  > "$RAW_DIR/bubble_color_on.visual.txt"

if cmp -s "$RAW_DIR/bubble_color_off.visual.txt" "$RAW_DIR/bubble_color_on.visual.txt"; then
  BUBBLE_COLOR_CHECK="FAIL (visual outputs are identical)"
else
  BUBBLE_COLOR_CHECK="PASS (visual outputs differ)"
fi

render_visual_png bubble_color_effect "bubble color effect review" \
  bubble -f "$ROOT_DIR/data/titanic.csv" \
  --cols Cabin --cols Age --cols Embarked --y Name --color Pclass --head 12

GENERATED_AT="$(date -u +'%Y-%m-%d %H:%M:%S UTC')"
REPORT_FILE="$OUT_DIR/REPORT.md"

cat > "$REPORT_FILE" <<EOF
# Design Review Artifacts

Generated: $GENERATED_AT

This folder is generated by:

\`\`\`bash
bash scripts/generate_design_review_images.sh
\`\`\`

## Scenario Artifacts

- Timeline: [timeline_legend.png](images/timeline_legend.png), [timeline_zoom.png](images/timeline_zoom.png)
- Bar: [bar_distribution.png](images/bar_distribution.png), [bar_sort_top.png](images/bar_sort_top.png)
- Line: [line_trend.png](images/line_trend.png), [line_head.png](images/line_head.png)
- Bubble: [bubble_matrix.png](images/bubble_matrix.png), [bubble_top.png](images/bubble_top.png), [bubble_color_effect.png](images/bubble_color_effect.png)

### Timeline Preview
![timeline_legend](images/timeline_legend.png)
![timeline_zoom](images/timeline_zoom.png)

### Bar Preview
![bar_distribution](images/bar_distribution.png)
![bar_sort_top](images/bar_sort_top.png)

### Line Preview
![line_trend](images/line_trend.png)
![line_head](images/line_head.png)

### Bubble Preview
![bubble_matrix](images/bubble_matrix.png)
![bubble_top](images/bubble_top.png)
![bubble_color_effect](images/bubble_color_effect.png)

Raw command outputs are in \`raw/\`.

## Automated Checks

- Bubble \`--color\` effect: $BUBBLE_COLOR_CHECK
EOF

echo "Design review artifacts updated in $OUT_DIR"
